# -*- coding: utf-8 -*-
"""HOMEWORK Week 3 - Customer Segmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MGsHZnKaW8G-cKXrigSAgbCzz6lGcZ47
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans
from sklearn.metrics import pairwise_distances_argmin

"""Load the CSV. Drop CustomerID (it's just an ID)."""

url = "https://raw.githubusercontent.com/SteffiPeTaffy/machineLearningAZ/master/Machine%20Learning%20A-Z%20Template%20Folder/Part%204%20-%20Clustering/Section%2025%20-%20Hierarchical%20Clustering/Mall_Customers.csv"

df = pd.read_csv(url)

print(df.head())

df = df.drop('CustomerID', axis=1) #to drop columns

"""Show first 5 rows, .info(), and .describe()."""

df.info()

df.describe()

"""Part 2: Features & Scaling
Use these features for clustering:
Annual Income (k$)
Spending Score (1-100)
Build X with those columns.
Standardize with StandardScaler.
"""

X = df[["Annual Income (k$)", "Spending Score (1-100)"]]  # features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

"""Part 3: K‑Means: Choose K (Elbow & Silhouette)
Elbow method:
For  K=1  to  10 , fit K‑Means on scaled data and record inertia (WCSS).
Plot WCSS vs K.

"""

wcss = [] # INERTIA: The sum of distances between points and their centroid. As  K  increases, Inertia decreases
k_range = range(1, 11)

for k in k_range:
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(X_scaled)
    wcss.append(kmeans.inertia_)

plt.figure(figsize=(6, 5))
plt.plot(k_range, wcss, marker='o', linestyle='--')
plt.title('The Elbow Method ((WCSS vs K))')
plt.xlabel('Number of clusters (K)')
plt.ylabel('WCSS (Inertia)')
plt.annotate('The Elbow (Optimal K)', xy=(5, wcss[4]), xytext=(6, 200),
             arrowprops=dict(facecolor='black', shrink=0.05))
plt.show()

"""Silhouette score:
For  K=2  to  10 , compute Silhouette Score.
Plot Silhouette Score vs K.
Briefly discuss which K looks reasonable
"""

from sklearn.metrics import silhouette_score

silhouette_scores = []
k_range = range(2, 11)  # silhouette is not defined for K=1

for k in k_range:
    kmeans = KMeans(
        n_clusters=k,
        init="k-means++",
        n_init=10,
        max_iter=300,
        random_state=42
    )
    labels = kmeans.fit_predict(X_scaled)
    score = silhouette_score(X_scaled, labels)
    silhouette_scores.append(score)

# plot


plt.figure(figsize=(7, 4))
plt.plot(k_range, silhouette_scores, marker='o', linestyle='--', color='purple')
plt.title("Silhouette Score for  K")
plt.xlabel("Number of Clusters (K)")
plt.ylabel("Silhouette Score")

# Highlight the best K
best_k_idx = np.argmax(silhouette_scores)
best_k = list(k_range)[best_k_idx]
best_score = silhouette_scores[best_k_idx]

plt.scatter(best_k, best_score, color='red', s=100, zorder=5, label=f'Best K = {best_k}')
plt.legend()
plt.show()

"""From Elbow plot we see that the curve flattens just after K=5 wich means that the aditional clusters wont improve the model, the improves are marginal.
From Silhouette, we see that the higher score is 5, that indicates relevant clusters, evaluating how good each data points is correctly fitted with its assigned cluster and how separate is from the others. A higher score indicates a better clustering result.

Part 4: Final K‑Means Model (K = 5) & Strategy
Fit K‑Means with  K=5  on the scaled data.
Add the cluster labels to the original DataFrame.
Make a scatter plot:
x-axis: Annual Income (k$)
y-axis: Spending Score (1-100)
Color by cluster and show centroids.
"""

k_optimal = 5  # from visual inspection of the elbow curve and silhouette score
kmeans_sklearn = KMeans(
    n_clusters=k_optimal,
    init="k-means++",       # smarter initialization than random
    n_init=10,              # run the algorithm with 10 different centroid seeds
    max_iter=300,           # maximum iterations for a single run
    random_state=42
)

kmeans_sklearn.fit(X_scaled)

labels_sklearn = kmeans_sklearn.labels_
centers_sklearn = kmeans_sklearn.cluster_centers_ # scaled info

df["Cluster_Kmeans"]=labels_sklearn

df.head()

#  Centroids to original because they were scaled
centers_original = scaler.inverse_transform(centers_sklearn)

# Scatter plot in ORIGINAL scale
plt.figure(figsize=(10, 6))
plt.scatter(
    X.iloc[:, 0],          # Annual Income (k$)
    X.iloc[:, 1],          # Spending Score (1-100)
    c=labels_sklearn,
    s=40,
    cmap="viridis",
    alpha=0.7,
    label="Customers"
)

plt.scatter(
    centers_original[:, 0],
    centers_original[:, 1],
    c="red",
    s=250,
    marker="X",
    edgecolors="black",
    label="Centroids"
)

plt.title(f"K-Means Clustering with K={k_optimal}")
plt.xlabel("Annual Income (k$)")
plt.ylabel("Spending Score (1-100)")
plt.legend()
plt.show()

"""
Create a small table: for each cluster, show mean Age, Annual Income, Spending Score and cluster size.
Write some comments for each of your 5 clusters:
Who is in the cluster (age, income, spending pattern)?
What can be the strategy for them (e.g., products, marketing focus)?"""

cluster_summary_kmeans = df.groupby("Cluster_Kmeans").agg(
    mean_age=("Age", "mean"),
    mean_income=("Annual Income (k$)", "mean"),
    mean_spending=("Spending Score (1-100)", "mean"),
    cluster_size=("Cluster_Kmeans", "count")
).round(2)

cluster_summary_kmeans

"""- Cluster 0: mid age- with mid income and a mid spending. Most regular group
-Cluster 1:Younger, with higher income and higher expenditure
-Cluster 2: They youngest clouster with the lower income and a high spending behaviour
-Cluster 3: Mid age- with higher income and low spending. Maybe rationals ones
-Cluster 4: Older Group- low income and low spending

The strategy is: keep Cluster 0 loyal with simple promos and treat Cluster 1 like VIPs with exclusive offers and premium products, target Cluster 2 with discounts and bundles because they spend a lot but are price-sensitive, try to activate Cluster 3 with more personalized campaigns since they have high income but low spending, and for Cluster 4 just use basic, low-cost mass marketing without investing too much.

Part 5: DBSCAN on Mall Customers
Use the same 2 features: Annual Income (k$) and Spending Score (1-100) (scaled).
Run DBSCAN (try to find the optimal  ϵ  using the k-Distance Graph with MinPts calculated using the rule of thumb in the slide).
Pick one  ϵ  in the knee area that gives a reasonable number of clusters plus maybe some noise.
Plot customers:
x-axis: Income
y-axis: Spending Score
Color by DBSCAN cluster, noise as black.
"""

from sklearn.neighbors import NearestNeighbors
from sklearn.cluster import DBSCAN


#  k-distance graph
MinPts = 4

nbrs = NearestNeighbors(n_neighbors=MinPts).fit(X_scaled)
distances, indices = nbrs.kneighbors(X_scaled)
k_distances = np.sort(distances[:, -1])

plt.figure(figsize=(7, 4))
plt.plot(k_distances)
plt.title(f"{MinPts}-Distance Graph (Mall Customers)")
plt.xlabel("Points sorted by distance")
plt.ylabel(f"Distance to {MinPts}-th nearest neighbor")
plt.grid(True)
plt.show()

eps_value = 0.4   #KNEE

dbscan_mall = DBSCAN(eps=eps_value, min_samples=MinPts)
labels_dbscan = dbscan_mall.fit_predict(X_scaled)


df["Cluster_DBSCAN"] = labels_dbscan

df["Cluster_DBSCAN"].value_counts()

mask_noise = df["Cluster_DBSCAN"] == -1
mask_cluster = df["Cluster_DBSCAN"] != -1

plt.figure(figsize=(8, 5))

# Clusters
plt.scatter(
    df.loc[mask_cluster, "Annual Income (k$)"],
    df.loc[mask_cluster, "Spending Score (1-100)"],
    c=df.loc[mask_cluster, "Cluster_DBSCAN"],
    cmap="viridis",
    s=40,
    alpha=0.8,
    label="Clusters"
)

# Noise
plt.scatter(
    df.loc[mask_noise, "Annual Income (k$)"],
    df.loc[mask_noise, "Spending Score (1-100)"],
    c="black",
    s=50,
    alpha=0.9,
    label="Noise"
)

plt.title(f"DBSCAN on Mall Customers (eps={eps_value}, MinPts={MinPts})")
plt.xlabel("Annual Income (k$)")
plt.ylabel("Spending Score (1-100)")
plt.legend()
plt.grid(True)
plt.show()

"""Create a small table: for each cluster, show mean Age, Annual Income, Spending Score and cluster size. Compare these clusters with those from K-Means.
Identify some outliers and give comments about them.
Give some comments comparing K‑Means vs DBSCAN for this dataset:
Which is easier to tune?
Which gives more interpretable segments for marketing?
Which would you use for this segmentation task, and why?
"""

dbscan_summary = df[df["Cluster_DBSCAN"] != -1].groupby("Cluster_DBSCAN").agg(
    mean_age=("Age", "mean"),
    mean_income=("Annual Income (k$)", "mean"),
    mean_spending=("Spending Score (1-100)", "mean"),
    cluster_size=("Cluster_DBSCAN", "count")
).round(2)

dbscan_summary

"""For this dataset, K-Means is easier to tune: I just choose K using the elbow and the silhouette score. DBSCAN needs two parameters (eps and MinPts) and the result changes a lot with eps. In terms of marketing, K-Means gives 5 clean and balanced segments that are easy to explain and use for campaigns, while DBSCAN gives more flexible shapes and identifies a few outliers, but the segments are less regular. For this mall segmentation task I would use K-Means for the main customer groups and DBSCAN only to highlight unusual customers (noise points)."""
